name: SVG Generator
on:
    workflow_dispatch:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install drawio-python

      - name: Generate SVG
        run: |
          python3 -m drawio.drawio_to_svg de-poc-etl-wfs/GCP_Diagram.xml GCP_Diagram.svg

      - name: Upload SVG
        uses: actions/upload-artifact@v2
        with:
          name: GCP_Diagram.svg
          path: de-poc-etl-wfs/GCP_Diagram.svg
